### ISSUE TITLE
Create Login and Profil Page

### ISSUE THREAD

**Issue by OliverNeuhaeusler** [OliverNeuhaeusler/mittelaltermarkt-app#11]
**Storyname**
Profil and Login

**Value Statement**
As a user you can create a prolie that the user can create a market and a pforile page

**Acception Criteria**
+ create profile
+ you uploud a image from you
+ you now create markets

**Task`s**
- [ ] new branch loginandprofile
- [ ] add profile and ligin components
- [ ] Implement logic for ecerything
