### ISSUE TITLE
Mittelaltermarkt Karte

### ISSUE THREAD

**Issue by OliverNeuhaeusler** [OliverNeuhaeusler/mittelaltermarkt-app#5]
**Storyname**
Card for the Mittelaltermarkt page

**Value Statement**
As a user you can see the name of the Market, pics, a short description, you can commit, you can give stars, show were the market is and you can make a detailed show for more informations
And you can favorite,

**Acception Criteria**
+ Scroll on the page for show markets
+ you can click on the fav icon to put the market in the favs.
+ you can commit the market 
+ you can rate the Market.
+ you can look on Googlemaps where the market is an how far it is.
+ you can click the detailsbutton to show more details.

**Task`s**
- [x] new branch mittelaltercard
- [x] add card components
- [x] Implement logic for ecerything
- [x] add tests.
